CREATE TABLE IF NOT EXISTS metrics
(
    id
    INTEGER
    PRIMARY
    KEY,
    metric_name
    TEXT
    NOT
    NULL,
    description
    TEXT
    NOT
    NULL,
    blog_link
    TEXT
    NULL,
    video_link
    TEXT
    NULL,
    units
    TEXT
    NOT
    NULL
);

DELETE
FROM metrics;

INSERT
OR IGNORE INTO metrics (id,
                               metric_name,
                               description,
                               blog_link,
                               video_link,
                               units)
VALUES (1,
        'Net Promoter Score',
        'Net Promoter Score (NPS) measures customer loyalty and likelihood to recommend a product or service, calculated by subtracting the percentage of Detractors (0-6 rating) from Promoters (9-10 rating) on a 0-10 scale. NPS serves as a predictive indicator of business growth potential.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/csat-nps',
        'https://youtu.be/7403IcyqmPE',
        'Percentage'),
       (2,
        'Customer Satisfaction Score (CSAT)',
        'Customer Satisfaction Score (CSAT) quantifies customer sentiment by measuring satisfaction with specific interactions, features, or overall experience. Typically collected through surveys using a 1-5 or 1-10 scale, CSAT provides immediate feedback on product performance and service quality.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/csat-nps',
        'https://youtu.be/7403IcyqmPE',
        'Percentage'),
       (3,
        '% of Roadmap Delivered Quarterly',
        'This metric tracks the proportion of planned product features and improvements successfully delivered within each quarter relative to the established roadmap. It measures execution effectiveness, development velocity, and the organization''s ability to meet strategic commitments.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/percentage-roadmap-delivered-quarterly',
        'https://youtu.be/NRLMHfJAFmo',
        'Percentage'),
       (4,
        'Average Release Cycle Time',
        'Average Release Cycle Time measures the mean duration between successive software releases, from initiation to deployment. This metric reflects development efficiency, quality control processes, and the organization''s agility in responding to market needs and customer feedback.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/release-cycle-time',
        'https://youtu.be/afsgz1L8crM',
        'Days'),
       (5,
        '% of Users ''Very Disappointed'' if Product is Removed',
        'This metric quantifies the percentage of users who would be "very disappointed" if they could no longer access your product, typically measured through surveys. A high percentage (>40%) indicates strong product-market fit and genuine user dependency, predicting retention and growth potential.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/very-disappointed-user-metric',
        'https://youtu.be/xpIFfuQCmPE',
        'Percentage'),
       (6,
        '% of Features Used by >50% of Users',
        'This metric measures the proportion of product features that achieve majority adoption (used by over 50% of the user base). It indicates feature relevance, product-market fit, and development efficiency by revealing which capabilities deliver value to most customers versus those with limited utilization.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/feature-usage-metric',
        'https://youtu.be/me-A7VFpHa0',
        'Percentage'),
       (7,
        'Customer Retention Rate (CRR)',
        'Customer Retention Rate (CRR) quantifies the percentage of customers retained over a specific timeframe, excluding new acquisitions. Calculated as ((E-N)/S) × 100, where E represents end-period customers, N represents new customers acquired, and S represents start-period customers.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/customer-retention-rate',
        'https://youtu.be/MUcjhslef-g',
        'Percentage'),
       (8,
        'Monthly Churn Rate',
        'Monthly Churn Rate is the percentage of subscribers who cancel recurring services within a month. High churn signals product-market misalignment or competitive weaknesses, necessitating retention strategies.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/monthly-churn-rate',
        'https://youtu.be/AOydX68dr_c',
        'Percentage'),
       (9,
        'Net Revenue Retention (NRR)',
        'Net Revenue Retention (NRR) measures a SaaS company''s ability to retain and grow revenue from existing customers over a specific period. Calculated as (current period revenue from existing customers ÷ prior period revenue from same customers) × 100%, NRR captures expansion, contraction, and churn effects.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/net-revenue-retention',
        'https://youtu.be/gQn2fx1fEOY',
        'Percentage'),
       (10,
        'Annual Recurring Revenue (ARR)',
        'Annual Recurring Revenue (ARR) is the normalized value of contracted recurring revenue components from term subscriptions calculated on a 12-month basis. ARR excludes one-time fees and typically includes yearly subscription revenue plus upgrades minus downgrades and churn, providing visibility into long-term business health.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/recurring-revenue',
        'https://youtu.be/PQBrqNgC10E',
        'Percentage'),
       (11,
        'Monthly Recurring Revenue (MRR)',
        'Monthly Recurring Revenue (MRR) represents the predictable or confirmed revenue generated from all active subscriptions in a given month. It excludes one-time payments, free trials, and temporary discounts, focusing solely on stable, recurring revenue components to facilitate short-term financial planning and performance tracking.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/recurring-revenue',
        'https://youtu.be/PQBrqNgC10E',
        'Percentage'),
       (12,
        'Branded Search Traffic',
        'It refers to website visits originating from search engine queries containing specific brand-related keywords, such as a company’s name, product names, or unique service identifiers.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/branded-search-traffic-unaided-brand-recall',
        'https://youtu.be/-PKY7sJ8R2s',
        'Percentage'),
       (13,
        'Unaided Brand Recall',
        'Ask someone "What companies make project management software?" The names they list without any hints? That''s unaided brand recall. It''s the brands that live in people''s heads, ready to be mentioned at a moment''s notice.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/branded-search-traffic-unaided-brand-recall',
        'https://youtu.be/-PKY7sJ8R2s',
        'Percentage'),
       (14,
        'Gross Margin',
        'Gross margin measures the percentage of revenue remaining after deducting direct costs of delivering services (COGS). For SaaS companies, this metric reflects operational efficiency in converting revenue to gross profit before accounting for fixed costs like R&D and marketing.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/gross-margin',
        'https://youtu.be/tKPigwoPyg0',
        'Percentage'),
       (15,
        'LTC:CAC Ratio',
        'The LTV:CAC ratio quantifies the relationship between the lifetime value (LTV) of a customer and the cost to acquire that customer (CAC).',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/ltv-cac-ratio',
        'https://youtu.be/-XH4mqWXHTY',
        'Ratio'),
       (16,
        'Percentage of Features with Clear Monetization Path',
        'The "Percentage of Features with Clear Monetization Path" measures how much of your SaaS product drives revenue.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/feature-monetization-metric',
        'https://youtu.be/JRZ-ozHfxxI',
        'Percentage'),
       (17,
        'Customer Acquisition Cost (CAC) Payback Period',
        'CAC payback period (CPP) measures how many months it takes to recover what you spent to acquire a customer, after accounting for the costs of serving them.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/cac-payback-period',
        'https://youtu.be/Z_fW8rijIwk',
        'Months'),
       (18,
        'Net Dollar Retention',
        'Net Dollar Retention shows how much money a company keeps from its current customers over time.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/net-dollar-retention',
        'https://youtu.be/pdz7sw2nrRQ',
        'Percentage'),
       (19,
        'ARR Growth Rate',
        'ARR Growth Rate (YoY) measures the percentage change in ARR over consecutive 12-month periods.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/arr-mrr-growth-rate',
        'https://youtu.be/VbUtKwDu9UI',
        'Percentage'),
       (20,
        'MRR Growth Rate',
        'MRR Growth Rate (MoM) measures how quickly your monthly revenue(MRR) is growing, as a percentage.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/arr-mrr-growth-rate',
        'https://youtu.be/VbUtKwDu9UI',
        'Percentage'),
       (21,
        '% Revenue from Upsell',
        'Upselling refers to the strategy of encouraging existing customers to upgrade to a higher-tier version of the same product they already use.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/upsell-crosssell',
        'https://youtu.be/HsoAXZXDM9g',
        'Percentage'),
       (22,
        '% Revenue from Cross-sell',
        'Cross-selling involves offering additional products or complementary features that supplement the customer''s initial purchase.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/upsell-crosssell',
        'https://youtu.be/HsoAXZXDM9g',
        'Percentage'),
       (23,
        'Net Burn Rate',
        'Net Burn Rate measures the rate at which a SaaS company consumes its cash reserves after accounting for revenue generated during the same period. It reflects the net cash loss per month or quarter.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/net-burn-rate-vs-burn-multiple',
        'https://youtu.be/2KxwMaHO1JE',
        'Currency per period'),
       (24,
        'Burn Multiple',
        'Burn Multiple quantifies capital efficiency by measuring how much cash a company burns to generate $1 of new Annual Recurring Revenue (ARR).',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/net-burn-rate-vs-burn-multiple',
        'https://youtu.be/2KxwMaHO1JE',
        'Rate'),
       (25,
        'Annual Recurring Revenue (ARR) per Employee or Revenue Efficiency',
        'Revenue efficiency in SaaS is quantified as Annual Recurring Revenue (ARR) per employee, a metric that divides a company’s total ARR by its full-time equivalent (FTE) headcount. This ratio measures the average recurring revenue generated per employee, serving as a barometer of operational efficiency and workforce productivity.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/revenue-efficiency',
        'https://youtu.be/TDZSursOWcE',
        'Currency'),
       (26,
        'Earnings Before Interest, Taxes, Depreciation & Amortization (EBITDA)',
        'Earnings Before Interest, Taxes, Depreciation & Amortization is a measure of a company''s operational profitability, excluding non-operational expenses and non-cash accounting charges.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/ebitda-cagr-rule-of-40',
        'https://youtu.be/w-ZKs_JR3J8',
        'Currency'),
       (27,
        'Earnings Before Interest, Taxes, Depreciation & Amortization (EBITDA) Margin',
        'Shows EBITDA as a percentage of its total revenue.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/ebitda-cagr-rule-of-40.',
        'https://youtu.be/w-ZKs_JR3J8',
        'Currency'),
       (28,
        'Compound Annual Growth Rate (CAGR)',
        'Compound Annual Growth Rate is the smoothed annualized growth rate of a metric (e.g., revenue) over a multi-year period, assuming steady growth.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/ebitda-cagr-rule-of-40',
        'https://youtu.be/w-ZKs_JR3J8',
        'Currency'),
       (29,
        'The Rule Of 40',
        'Combines EBITDA Margin + Revenue Growth Rate to evaluate the tradeoff between growth and profitability.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/ebitda-cagr-rule-of-40',
        'https://youtu.be/w-ZKs_JR3J8',
        'Currency');