CREATE TABLE IF NOT EXISTS metrics
(
    id          INTEGER PRIMARY KEY,
    metric_name TEXT NOT NULL,
    description TEXT NOT NULL,
    blog_link   TEXT NULL,
    video_link  TEXT NULL,
    units       TEXT NOT NULL
);

INSERT OR IGNORE INTO metrics (id,
                               metric_name,
                               description,
                               blog_link,
                               video_link,
                               units)
VALUES (1,
        'Net Promoter Score',
        'Net Promoter Score (NPS) measures customer loyalty and likelihood to recommend a product or service, calculated by subtracting the percentage of Detractors (0-6 rating) from Promoters (9-10 rating) on a 0-10 scale. NPS serves as a predictive indicator of business growth potential.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/csat-nps',
        'https://youtu.be/7403IcyqmPE',
        'Percentage'),
       (2,
        'Customer Satisfaction Score (CSAT)',
        'Customer Satisfaction Score (CSAT) quantifies customer sentiment by measuring satisfaction with specific interactions, features, or overall experience. Typically collected through surveys using a 1-5 or 1-10 scale, CSAT provides immediate feedback on product performance and service quality.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/csat-nps',
        'https://youtu.be/7403IcyqmPE',
        'Percentage'),
       (3,
        '% of Roadmap Delivered Quarterly',
        'This metric tracks the proportion of planned product features and improvements successfully delivered within each quarter relative to the established roadmap. It measures execution effectiveness, development velocity, and the organization''s ability to meet strategic commitments.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/percentage-roadmap-delivered-quarterly',
        'https://youtu.be/NRLMHfJAFmo',
        'Percentage'),
       (4,
        'Average Release Cycle Time',
        'Average Release Cycle Time measures the mean duration between successive software releases, from initiation to deployment. This metric reflects development efficiency, quality control processes, and the organization''s agility in responding to market needs and customer feedback.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/release-cycle-time',
        'https://youtu.be/afsgz1L8crM',
        'Days'),
       (5,
        '% of Users ''Very Disappointed'' if Product is Removed',
        'This metric quantifies the percentage of users who would be "very disappointed" if they could no longer access your product, typically measured through surveys. A high percentage (>40%) indicates strong product-market fit and genuine user dependency, predicting retention and growth potential.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/very-disappointed-user-metric',
        'https://youtu.be/xpIFfuQCmPE',
        'Percentage'),
       (6,
        '% of Features Used by >50% of Users',
        'This metric measures the proportion of product features that achieve majority adoption (used by over 50% of the user base). It indicates feature relevance, product-market fit, and development efficiency by revealing which capabilities deliver value to most customers versus those with limited utilization.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/feature-usage-metric',
        'https://youtu.be/me-A7VFpHa0',
        'Percentage'),
       (7,
        'Customer Retention Rate (CRR)',
        'Customer Retention Rate (CRR) quantifies the percentage of customers retained over a specific timeframe, excluding new acquisitions. Calculated as ((E-N)/S) × 100, where E represents end-period customers, N represents new customers acquired, and S represents start-period customers.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/customer-retention-rate',
        'https://youtu.be/MUcjhslef-g',
        'Percentage'),
       (8,
        'Monthly Churn Rate',
        'Monthly Churn Rate is the percentage of subscribers who cancel recurring services within a month. High churn signals product-market misalignment or competitive weaknesses, necessitating retention strategies.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/monthly-churn-rate',
        'https://youtu.be/AOydX68dr_c',
        'Percentage'),
       (9,
        'Net Revenue Retention (NRR)',
        'Net Revenue Retention (NRR) measures a SaaS company''s ability to retain and grow revenue from existing customers over a specific period. Calculated as (current period revenue from existing customers ÷ prior period revenue from same customers) × 100%, NRR captures expansion, contraction, and churn effects.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/net-revenue-retention',
        'https://youtu.be/gQn2fx1fEOY',
        'Percentage'),
       (10,
        'Annual Recurring Revenue (ARR)',
        'Annual Recurring Revenue (ARR) is the normalized value of contracted recurring revenue components from term subscriptions calculated on a 12-month basis. ARR excludes one-time fees and typically includes yearly subscription revenue plus upgrades minus downgrades and churn, providing visibility into long-term business health.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/recurring-revenue',
        'https://youtu.be/PQBrqNgC10E',
        'Percentage'),
       (11,
        'Monthly Recurring Revenue (MRR)',
        'Monthly Recurring Revenue (MRR) represents the predictable or confirmed revenue generated from all active subscriptions in a given month. It excludes one-time payments, free trials, and temporary discounts, focusing solely on stable, recurring revenue components to facilitate short-term financial planning and performance tracking.',
        'https://skyfeatherstudios.wixstudio.com/minimalist/post/recurring-revenue',
        'https://youtu.be/PQBrqNgC10E',
        'Percentage');