CREATE TABLE IF NOT EXISTS architecture_growth_stage_metric_associations
(
    id                     INTEGER PRIMARY KEY AUTOINCREMENT,
    growth_stage_id        INTEGER        NOT NULL,
    architecture_pillar_id INTEGER        NOT NULL,
    saas_type_id                          NULL,
    industry_id                           NULL,
    metric_id                             NOT NULL,
    min_value              DECIMAL(10, 2) NOT NULL,
    max_value              DECIMAL(10, 2) NOT NULL,
    lo_range_value         DECIMAL(10, 2) NOT NULL,
    hi_range_value         DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (growth_stage_id) REFERENCES growth_stages (id),
    FOREIGN KEY (architecture_pillar_id) REFERENCES architecture_pillars (id),
    FOREIGN KEY (saas_type_id) REFERENCES saas_types (id),
    FOREIGN KEY (industry_id) REFERENCES industries (id),
    FOREIGN KEY (metric_id) REFERENCES metrics (id)
);

CREATE INDEX IF NOT EXISTS idx_architecture_growth_stage_metric_associations
    ON architecture_growth_stage_metric_associations (architecture_pillar_id, growth_stage_id, metric_id);

DELETE
FROM architecture_growth_stage_metric_associations;

INSERT INTO architecture_growth_stage_metric_associations(id,
                                                          growth_stage_id,
                                                          architecture_pillar_id,
                                                          saas_type_id,
                                                          industry_id,
                                                          metric_id,
                                                          min_value,
                                                          max_value,
                                                          lo_range_value,
                                                          hi_range_value)
VALUES (1,
        2,
        1,
        NULL,
        NULL,
        1,
        0,
        100,
        20,
        35),
       (2,
        3,
        1,
        NULL,
        NULL,
        1,
        0,
        100,
        35,
        50),
       (3,
        4,
        1,
        NULL,
        NULL,
        1,
        0,
        100,
        50,
        65),
       (4,
        5,
        1,
        NULL,
        NULL,
        1,
        0,
        100,
        60,
        75),
       (5,
        2,
        1,
        NULL,
        NULL,
        2,
        0,
        100,
        65,
        80),
       (6,
        3,
        1,
        NULL,
        NULL,
        2,
        0,
        100,
        75,
        85),
       (7,
        4,
        1,
        NULL,
        NULL,
        2,
        0,
        100,
        85,
        92),
       (8,
        5,
        1,
        NULL,
        NULL,
        2,
        0,
        100,
        90,
        95),
         (9,
        2,
        2,
        1,
        NULL,
        4,
        0,
        90,
        3,
        5),
        (10,
        2,
        2,
        2,
        NULL,
        4,
        0,
        90,
        7,
        8),
        (11,
        3,
        2,
        1,
        NULL,
        4,
        0,
        90,
        5,
        8),
        (12,
        3,
        2,
        2,
        NULL,
        4,
        0,
        90,
        10,
        14),
        (13,
        4,
        2,
        1,
        NULL,
        4,
        0,
        90,
        7,
        12),
        (14,
        4,
        2,
        2,
        NULL,
        4,
        0,
        90,
        12,
        18),
        (15,
        5,
        2,
        1,
        NULL,
        4,
        0,
        90,
        10,
        14),
        (16,
        5,
        2,
        2,
        NULL,
        4,
        0,
        90,
        14,
        21);