[theme]
# Set the default theme to "light"
base = "light"

[server]
maxUploadSize = 1024
enableCORS = false
enableXsrfProtection = true
enableStaticServing = true

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
enableFileLogging = true
logFilePath = "logs/app.log"
